title: trort's personal blog
author: trort

description: >-
  A personal tech blog powered by Jekyll and the Minima theme.
baseurl: ""
url: "https://trort.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
